port = 1323
process_name = "trailer_manager"
allow_origins = ["http://localhost:80"]

[broker]
host = "0.0.0.0"
port = 1883
clientId = "trailer_manager"
topics = ["gps/log"]

[rdb]
driver = "postgres"
host = "127.0.0.1"
port = 5432
dbname = "trailer_manager"
username = "root"
password = "secret"
